---
- name: Copy file from server1 to server2
  hosts: 172.31.8.185
  tasks:
    - name: Fetch file from Server1
      fetch:
        src: file100
        dest: /tmp

- name: Copy file to server2 from Controller
  hosts: 172.31.5.44
  tasks:
    - name: Copy file to Server2
      copy:
        src: /tmp/172.31.8.185
        dest: /tmp   
...          
