---
- name: Implementing when conditions
  hosts: all
  vars:
    - a: 10
  tasks:
    - name: Create user
      user:
        name: Ravi
        password: intelliqit
        home: /home/Ravi
        comment: 'A normal user'
        shell: /bin/bash
      when: a == 20     
...
