---
- name: Create multiple nginx containers
  hosts: all
  tasks: 
   - name: Create 10 nginx containers
     docker_container:
       name: "container{{item}}"
       image: nginx
     with_sequence: count=10

...       
