---
- name: Implementing Jenkins & Tomcat for CI-CD
  hosts: all
  tasks: 
    - name: Create Jenkins container
      docker_container:
        name: myjenkins
        image: jenkins/jenkins
        ports:
          - 5050:8080

    - name: Create tomcat as QA Server and prodserver
      docker_container:
        name: "{{item.a}}"
        image: tomcat
        ports:
          - "{{item.b}}"
        links:
          - myjenkins:jenkins

      with_items:
        - {a: qaserver,b: "6060:8080"}
        - {a: prodserver,b: "7070:8080"} 

...

