---
- name: Create users and copy files in to the users home dir
  hosts: all
  tasks:
   - name: Create multiple users
     user:
       name: "{{item.a}}"
       password: "{{item.b}}"
       home: "{{item.c}}"
     with_items:
       - {a: Ramesh, b: intelliqit, c: /home/Ramesh}
       - {a: Rajesh, b: intelliqit, c: /home/Ramesh}
         
   - name: Copy files in to users home directory
     copy:
      src: "{{item.a}}"
      dest: "{{item.b}}"
     with_items: 
      - {a: /etc/passwd, b: /home/Ramesh}
      - {a: /etc/group, b: /tmp/Rajesh}  
        
...         

