---
- name: Install docker and required s/w'S
  hosts: all
  tasks:
   - name: Install python-pip
     apt:
       name: python3-pip
       state: present
       update_cache: yes
   - name: Download docker script and execute it and also install python-pip
     shell: "{{item}}"
     with_items:
        - curl -fsSL https://get.docker.com -o get-docker.sh
        - sh get-docker.sh
        - pip3 install docker-py

...          

