---
- name: Login in Dockerhub
  hosts: 172.31.5.44
  tasks:
    - name: Login
      docker_login: 
        username: packsudh
        password: Testing59
           

    - name: Upload the docker image
      docker_image:
        name: packsudh/nginx11
        source: local  
        push: yes
  

...          
